[package]
name = "rusty_crypt"
version = "0.1.0"
edition = "2024"
authors = ["Tina-1300"]
description = "Rust library allowing for a very quick and simple implementation of AES-GCM encryption"
license = "MIT"
keywords = ["api", "cryptography", "aes-gcm", "fast", "rusty_crypt"]
repository = "https://github.com/Tina-1300/rusty_crypt"
rust-version = "1.91.1"


[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
rand = "0.8"
thiserror = "2.0.19"



[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
debug-assertions = false # Remove debug assertions