[package]
name = "rusty_crypt"
version = "0.4.0"
edition = "2024"
authors = ["Tina-1300"]
description = "Rust library allowing for a very quick and simple implementation of AES-GCM encryption"
license = "MIT"
keywords = ["api", "cryptography", "aes-gcm", "rusty_crypt", "secure"]
repository = "https://github.com/Tina-1300/rusty_crypt"
rust-version = "1.97.1"

# Files included in crates.io package
include = [
    "src/**/*.rs",
    "tests/**/*.rs",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    "LICENSE",
]

[dependencies]
aes-gcm = "0.11.0"
base64 = "0.23.0"
thiserror = "2.0.19"
getrandom = "0.4.3"


[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
debug-assertions = false # Remove debug assertions
